---
language: objective-c

before_script:
  - sudo easy_install cpp-coveralls

script:
 - xctool -project genstrings2.xcodeproj -scheme "Static Library" test -arch x86_64 ONLY_ACTIVE_ARCH=NO
### disabled until Travis-CI fixes missing appledoc install on 10.9 machines
# - appledoc -o /tmp .

after_success:
  - ./coveralls.rb --extension m --exclude-folder Demo --exclude-folder Test --exclude-folder Externals
