.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 29.12.11               \" DATE 
.Dt genstrings2 1      \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm genstrings2
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line. 
.\" Use .Nm macro to designate other names for the documented program.
.Nd generate string table from source code
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Fl noPositionalParameters              \" [-noPositionalParameters]
.Op Fl s Ar <routine>              \" [-s routine]
.Op Fl skipTable Ar <table>              \" [-skipTable table]
.Op Fl o Ar <outputDir>         \" [-o <outputDir>] 
.Ar                   \" [file ...]
.Sh DESCRIPTION          \" Section Header - required - don't modify
The 
.Nm
utility generates a .strings file(s) from C or Objective-C (.c or .m) source code file(s) given as the arguments(s). A
.Ar .strings
file is used for localizing an application for different languages, as described under "Internationalization" 
in the Cocoa Developer Documentation.

This utility is a complete rewrite of Apple's genstrings using modern techniques like GCD and designed to be more intelligent.
The original genstrings for example would crash whenever a macro would contain non-literal parameters.

* Format Strings and Positional Parameters:

Keys and values of string file entries can include formatting characters.  For value strings with multiple formatting arguments, positional parameters are generated.  These allow the order of arguments to be changed as needed by each localization (e.g. "File %1$@ contains %2$d bytes." could become "%2$d bytes are contained in file %1$@." in another localization).

* Encoding:

.Nm
tries to read souce code files regardless of their string format.

Generated .strings files are UTF-16 encoded.  Host endianness is used unless the -bigEndian or -littleEndian option is specified.

.Sh OPTIONS
.Bl -tag -width - indent
.It Fl s Ar routine
 Substitutes routine for NSLocalizedString.  For example, 
 -s MyLocalString will catch calls to MyLocalString and 
 MyLocalStringFromTable. 
.It Fl q 
Turns off multiple key/value pairs warning
.It Fl skipTable Ar table
 Causes genstrings to skip over the file for 
.Ar Table .
 Note that any entries in this table will not be generated.
.It Fl noPositionalParameters
 Turns off generation of positional parameters.
.It Fl o Ar outputDir
 Specifies what directory the tables should be created in.
.El